# Via https://github.com/vmtyler/vagrant-lambda-python-build

# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
#!/bin/bash
sleep 10
sudo su -
yum install -y git docker
service docker start
docker pull quay.io/pypa/manylinux1_x86_64
docker run --name "aaa" quay.io/pypa/manylinux1_x86_64 /bin/sh -c "cd && yum update -y && mkdir /wheelhouse && \
yum install cyrus-sasl-devel zlib-devel -y && \
wget https://launchpad.net/libmemcached/1.0/1.0.18/+download/libmemcached-1.0.18.tar.gz && \
tar -xvf libmemcached-1.0.18.tar.gz && \
cd libmemcached-1.0.18 && \
./configure && \
make && \
make install && \ 
cd ../ && \
git clone -b 1.5.2 git://github.com/lericson/pylibmc/ && cd pylibmc && \
/opt/python/cp27-cp27mu/bin/pip wheel . -w /wheelhouse && \
auditwheel repair /wheelhouse/pylibmc-1.5.2-cp27-cp27mu-linux_x86_64.whl -w /wheelhouse"
docker cp aaa:/wheelhouse/pylibmc-1.5.2-cp27-cp27mu-manylinux1_x86_64.whl /vagrant/
SCRIPT


# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.synced_folder "./", "/vagrant", type: "virtualbox", disabled: false
  config.vm.provision "shell", inline: $script
end

